In [ ]:
!pip install -r requirements.txt

In [1]:
!pip list

Package                   Version
------------------------- ------------
absl-py                   2.3.1
accelerate                1.9.0
aiohappyeyeballs          2.6.1
aiohttp                   3.12.15
aiosignal                 1.4.0
anyio                     4.7.0
argon2-cffi               21.3.0
argon2-cffi-bindings      21.2.0
asttokens                 3.0.0
async-lru                 2.0.4
attrs                     25.3.0
babel                     2.16.0
beautifulsoup4            4.13.4
bitsandbytes              0.46.1
bleach                    6.2.0
brotlicffi                1.0.9.2
certifi                   2025.7.14
cffi                      1.17.1
charset-normalizer        3.4.2
comm                      0.2.1
contourpy                 1.3.3
cycler                    0.12.1
datasets                  4.0.0
debugpy                   1.8.11
decorator                 5.1.1
defusedxml                0.7.1
dill                      0.3.8
einops                    0.8.1
executing                 0.8.3
fastjsonschema            2.20.0
filelock                  3.13.1
flash_attn                2.8.3
fonttools                 4.59.0
frozenlist                1.7.0
fsspec                    2024.6.1
grpcio                    1.74.0
h11                       0.16.0
hf-xet                    1.1.5
httpcore                  1.0.9
httpx                     0.28.1
huggingface-hub           0.34.3
idna                      3.7
ipykernel                 6.29.5
ipython                   9.1.0
ipython_pygments_lexers   1.1.1
jedi                      0.19.2
Jinja2                    3.1.4
json5                     0.9.25
jsonschema                4.25.0
jsonschema-specifications 2023.7.1
jupyter_client            8.6.3
jupyter_core              5.8.1
jupyter-events            0.12.0
jupyter-lsp               2.2.5
jupyter_server            2.16.0
jupyter_server_terminals  0.5.3
jupyterlab                4.4.4
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
kiwisolver                1.4.8
Markdown                  3.8.2
MarkupSafe                3.0.2
matplotlib                3.10.5
matplotlib-inline         0.1.6
mistune                   3.1.2
mpmath                    1.3.0
multidict                 6.6.3
multiprocess              0.70.16
nbclient                  0.10.2
nbconvert                 7.16.6
nbformat                  5.10.4
nest-asyncio              1.6.0
networkx                  3.3
notebook                  7.4.4
notebook_shim             0.2.4
numpy                     2.1.2
nvidia-cublas-cu12        12.8.3.14
nvidia-cuda-cupti-cu12    12.8.57
nvidia-cuda-nvrtc-cu12    12.8.61
nvidia-cuda-runtime-cu12  12.8.57
nvidia-cudnn-cu12         9.7.1.26
nvidia-cufft-cu12         11.3.3.41
nvidia-cufile-cu12        1.13.0.11
nvidia-curand-cu12        10.3.9.55
nvidia-cusolver-cu12      11.7.2.55
nvidia-cusparse-cu12      12.5.7.53
nvidia-cusparselt-cu12    0.6.3
nvidia-nccl-cu12          2.26.2
nvidia-nvjitlink-cu12     12.8.61
nvidia-nvtx-cu12          12.8.55
overrides                 7.4.0
packaging                 25.0
pandas                    2.3.1
pandas-stubs              2.3.0.250703
pandocfilters             1.5.0
parso                     0.8.4
peft                      0.17.0
pexpect                   4.9.0
pillow                    11.0.0
pip                       25.1
platformdirs              4.3.7
prometheus_client         0.21.1
prompt-toolkit            3.0.43
propcache                 0.3.2
protobuf                  6.31.1
psutil                    7.0.0
ptyprocess                0.7.0
pure-eval                 0.2.2
pyarrow                   21.0.0
pycparser                 2.21
Pygments                  2.19.1
pyparsing                 3.2.3
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-dotenv             1.1.1
python-json-logger        3.2.1
pytz                      2025.2
PyYAML                    6.0.2
pyzmq                     26.2.0
referencing               0.30.2
regex                     2025.7.34
requests                  2.32.4
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.22.3
safetensors               0.5.3
seaborn                   0.13.2
Send2Trash                1.8.2
setuptools                78.1.1
six                       1.17.0
sniffio                   1.3.0
soupsieve                 2.5
stack-data                0.2.0
sympy                     1.13.3
tensorboard               2.20.0
tensorboard-data-server   0.7.2
terminado                 0.17.1
tinycss2                  1.4.0
tokenizers                0.21.4
torch                     2.7.1+cu128
torchaudio                2.7.1+cu128
torchvision               0.22.1+cu128
tornado                   6.5.1
tqdm                      4.67.1
traitlets                 5.14.3
transformers              4.54.1
triton                    3.3.1
typing_extensions         4.12.2
tzdata                    2025.2
urllib3                   2.5.0
wcwidth                   0.2.13
webencodings              0.5.1
websocket-client          1.8.0
Werkzeug                  3.1.3
wheel                     0.45.1
xxhash                    3.5.0
yarl                      1.20.1

In [2]:
# Import .env file into os env variables
from dotenv import load_dotenv
load_dotenv()

True

In [3]:
!huggingface-cli login --token $HF_TOKEN --add-to-git-credential

/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
⚠️  Warning: 'huggingface-cli login' is deprecated. Use 'hf auth login' instead.
Token is valid (permission: write).
The token `full_access` has been saved to /home/sobhan/.cache/huggingface/stored_tokens
Your token has been saved in your configured git credential helpers (manager).
Your token has been saved to /home/sobhan/.cache/huggingface/token
Login successful.
Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

In [4]:
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128,expandable_segments:True"

import torch
import gc

# Check GPU availability
print(f"GPU Available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU Name: {torch.cuda.get_device_name()}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")

GPU Available: True
GPU Name: NVIDIA GeForce RTX 3090
GPU Memory: 23.5 GB

In [5]:
from dataset_builder import MixtureDataBuilder
from llm_layer_pruner import LLMLayerPruner

# ---------------------------
# 1. Setup
# ---------------------------
model_name = "Qwen/Qwen2.5-1.5B"   # small for testing
pruner = LLMLayerPruner(
    model_name=model_name,
    default_percentages=[10, 20, 30, 40, 50],  # unified default percentages
    default_rank=16,
    default_max_heal_steps=500,
    default_max_qlora_steps=1000,
    blank_noise_std=0.01,
)

# Build separate Train/Val/Test mixtures with token budgets per domain:
builder = MixtureDataBuilder(pruner.tokenizer, max_length=512, seed=42, verbose=True)

token_targets_by_split = {
    "train": {"syntax": 200_000, "code": 200_000, "math": 200_000},
    "test": {"syntax": 50_000, "code": 50_000, "math": 50_000},
}

texts_by_split, lengths_by_split, summary_by_split = builder.build_split_mixtures(
    token_targets_by_split,
    val_from_train_when_missing=True,
    # order_of_splits=["test","validation","train"]  # optional, this is the default
)

# Make dataloaders (you can omit a split by leaving it out of token_targets_by_split)
loaders = builder.make_dataloaders_for_splits(
    texts_by_split,
    batch_sizes={"test": 8, "train": 2},
    num_workers=4,
    pin_memory=True,
    shuffle=False,
)

train_dl = loaders["train"]
eval_dl = loaders["test"]


# Path to your analysis CSVs from earlier steps
agg_csvs = {
    "weighted_mean": f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_weighted_mean.csv",
    # "minimax":       f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_minimax.csv",
}

# ---------------------------
# 2. Pre-heal pruning sweep
# ---------------------------
df_pre = pruner.run_single_shot_pruning_sweep(
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    train_dataloader=train_dl,
    strategies=["none", "tblock_blank", "tblock_avg", "tblock_lr_mean", "tblock_consensus"],
)
display(df_pre)

# ---------------------------
# 3. Single-layer heal sweep
# ---------------------------
df_heal = pruner.run_single_layer_heal_sweep(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    strategies=["tblock_blank", "tblock_avg", "tblock_lr_mean", "tblock_consensus"],
    lr=2e-4,
    max_steps=350,
    grad_accum=4,
)
display(df_heal)

# ---------------------------
# 4. Full-model QLoRA healing experiments
# ---------------------------
df_full = pruner.run_full_heal_experiments(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    qlora_lr=1e-4,
    max_qlora_steps=700,
    grad_accum=4,
)
display(df_full)

/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[Mixture] Fallback for domain 'code': requested 'test' but using 'train'
[Mixture] Built 'test': domains={'syntax': 50374, 'code': 50084, 'math': 50032} | used_splits={'syntax': 'test', 'code': 'train', 'math': 'test'}
[Mixture] Built 'train': domains={'syntax': 200046, 'code': 200126, 'math': 200034} | used_splits={'syntax': 'train', 'code': 'train', 'math': 'train'}

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.22it/s]

Baseline PPL: 12.409 (layers=28, hidden=1536)

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.08it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.08it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.04it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.05it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.07it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.77it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.75it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.77it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.07it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.48it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.77it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.82it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.79it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.77it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.80it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 21.25it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 21.25it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 21.23it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 21.22it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 21.22it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 24.34it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 24.26it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 24.23it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 24.25it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 24.35it/s]

[Pre-heal sweep] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_preheal_sweep.csv

,method,strategy,percent,selected_start,selected_end_inclusive,baseline_ppl,post_ppl,delta_ppl,inserted_idx,rank
0,weighted_mean,none,10,13,15,12.408719,11.563365,-0.845354,NaN,16
1,weighted_mean,tblock_blank,10,12,15,12.408719,12.194977,-0.213742,12.0,16
2,weighted_mean,tblock_avg,10,12,15,12.408719,12.123243,-0.285476,12.0,16
3,weighted_mean,tblock_lr_mean,10,12,15,12.408719,12.252200,-0.156519,12.0,16
4,weighted_mean,tblock_consensus,10,12,15,12.408719,12.221641,-0.187079,12.0,16
5,weighted_mean,none,20,11,16,12.408719,13.710756,1.302037,NaN,16
6,weighted_mean,tblock_blank,20,9,15,12.408719,16.040251,3.631532,9.0,16
7,weighted_mean,tblock_avg,20,9,15,12.408719,15.765839,3.357119,9.0,16
8,weighted_mean,tblock_lr_mean,20,9,15,12.408719,16.073602,3.664883,9.0,16
9,weighted_mean,tblock_consensus,20,9,15,12.408719,16.051596,3.642877,9.0,16
10,weighted_mean,none,30,9,16,12.408719,17.134082,4.725363,NaN,16
11,weighted_mean,tblock_blank,30,8,16,12.408719,19.716346,7.307627,8.0,16
12,weighted_mean,tblock_avg,30,8,16,12.408719,19.411582,7.002863,8.0,16
13,weighted_mean,tblock_lr_mean,30,8,16,12.408719,19.733177,7.324457,8.0,16
14,weighted_mean,tblock_consensus,30,8,16,12.408719,19.720212,7.311493,8.0,16
15,weighted_mean,none,40,8,18,12.408719,30.934981,18.526262,NaN,16
16,weighted_mean,tblock_blank,40,7,18,12.408719,40.012594,27.603875,7.0,16
17,weighted_mean,tblock_avg,40,7,18,12.408719,39.055418,26.646699,7.0,16
18,weighted_mean,tblock_lr_mean,40,7,18,12.408719,40.035429,27.626710,7.0,16
19,weighted_mean,tblock_consensus,40,7,18,12.408719,40.033488,27.624769,7.0,16
20,weighted_mean,none,50,7,20,12.408719,71.840211,59.431492,NaN,16
21,weighted_mean,tblock_blank,50,7,21,12.408719,167.876683,155.467964,7.0,16
22,weighted_mean,tblock_avg,50,7,21,12.408719,161.515002,149.106283,7.0,16
23,weighted_mean,tblock_lr_mean,50,7,21,12.408719,167.149121,154.740401,7.0,16
24,weighted_mean,tblock_consensus,50,7,21,12.408719,167.877872,155.469153,7.0,16

Heal@layer12:  54%|█████▎    | 1399/2607 [01:09<01:00, 20.01it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.62it/s]
Heal@layer12:  54%|█████▎    | 1399/2607 [01:09<01:00, 20.03it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.53it/s]
Heal@layer12:  54%|█████▎    | 1399/2607 [01:10<01:00, 19.94it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.57it/s]
Heal@layer12:  54%|█████▎    | 1399/2607 [01:09<01:00, 20.03it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.51it/s]
Heal@layer9:  54%|█████▎    | 1399/2607 [01:06<00:57, 21.11it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.18it/s]
Heal@layer9:  54%|█████▎    | 1399/2607 [01:06<00:57, 21.15it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.17it/s]
Heal@layer9:  54%|█████▎    | 1399/2607 [01:06<00:57, 21.16it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.13it/s]
Heal@layer9:  54%|█████▎    | 1399/2607 [01:05<00:56, 21.30it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.16it/s]
Heal@layer8:  54%|█████▎    | 1399/2607 [01:01<00:53, 22.70it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.49it/s]
Heal@layer8:  54%|█████▎    | 1399/2607 [01:01<00:53, 22.67it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.77it/s]
Heal@layer8:  54%|█████▎    | 1399/2607 [00:59<00:51, 23.53it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 19.27it/s]
Heal@layer8:  54%|█████▎    | 1399/2607 [01:02<00:54, 22.32it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.37it/s]
Heal@layer7:  54%|█████▎    | 1399/2607 [00:55<00:47, 25.35it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 20.72it/s]
Heal@layer7:  54%|█████▎    | 1399/2607 [00:55<00:47, 25.31it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 20.72it/s]
Heal@layer7:  54%|█████▎    | 1399/2607 [00:55<00:47, 25.36it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 20.74it/s]
Heal@layer7:  54%|█████▎    | 1399/2607 [00:55<00:48, 25.16it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 20.67it/s]
Heal@layer7:  54%|█████▎    | 1399/2607 [00:46<00:40, 30.06it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 23.79it/s]
Heal@layer7:  54%|█████▎    | 1399/2607 [00:46<00:40, 30.07it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 23.74it/s]
Heal@layer7:  54%|█████▎    | 1399/2607 [00:46<00:40, 30.06it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 23.76it/s]
Heal@layer7:  54%|█████▎    | 1399/2607 [00:46<00:39, 30.26it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 23.75it/s]

[Single-layer heal] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_single_layer_heal.csv

,method,strategy,percent,selected_start,selected_end_inclusive,ppl_before_heal,ppl_after_heal,delta_ppl,inserted_idx,rank
0,weighted_mean,tblock_blank,10,12,15,12.194977,10.285704,-1.909273,12,16
1,weighted_mean,tblock_avg,10,12,15,12.123243,9.806059,-2.317183,12,16
2,weighted_mean,tblock_lr_mean,10,12,15,12.252200,10.084854,-2.167346,12,16
3,weighted_mean,tblock_consensus,10,12,15,12.221641,10.199508,-2.022133,12,16
4,weighted_mean,tblock_blank,20,9,15,16.040251,11.240519,-4.799731,9,16
5,weighted_mean,tblock_avg,20,9,15,15.765839,10.740537,-5.025301,9,16
6,weighted_mean,tblock_lr_mean,20,9,15,16.073602,11.269462,-4.804140,9,16
7,weighted_mean,tblock_consensus,20,9,15,16.051596,11.295673,-4.755923,9,16
8,weighted_mean,tblock_blank,30,8,16,19.716346,12.652171,-7.064176,8,16
9,weighted_mean,tblock_avg,30,8,16,19.411582,11.711585,-7.699997,8,16
10,weighted_mean,tblock_lr_mean,30,8,16,19.733177,12.412343,-7.320833,8,16
11,weighted_mean,tblock_consensus,30,8,16,19.720212,12.532783,-7.187429,8,16
12,weighted_mean,tblock_blank,40,7,18,40.012594,15.619708,-24.392886,7,16
13,weighted_mean,tblock_avg,40,7,18,39.055418,14.199038,-24.856380,7,16
14,weighted_mean,tblock_lr_mean,40,7,18,40.035429,15.391331,-24.644099,7,16
15,weighted_mean,tblock_consensus,40,7,18,40.033488,15.865998,-24.167491,7,16
16,weighted_mean,tblock_blank,50,7,21,167.876683,23.031356,-144.845327,7,16
17,weighted_mean,tblock_avg,50,7,21,161.515002,20.986716,-140.528286,7,16
18,weighted_mean,tblock_lr_mean,50,7,21,167.149121,23.423824,-143.725296,7,16
19,weighted_mean,tblock_consensus,50,7,21,167.877872,23.835314,-144.042558,7,16

QLoRA-heal: 100%|██████████| 2607/2607 [05:35<00:00,  7.77it/s]
Perplexity: 100%|██████████| 164/164 [00:29<00:00,  5.63it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [05:35<00:00,  7.77it/s]
Perplexity: 100%|██████████| 164/164 [00:29<00:00,  5.63it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [05:13<00:00,  8.32it/s]
Perplexity: 100%|██████████| 164/164 [00:27<00:00,  5.99it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:49<00:00,  9.02it/s]
Perplexity: 100%|██████████| 164/164 [00:25<00:00,  6.42it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:49<00:00,  9.01it/s]
Perplexity: 100%|██████████| 164/164 [00:25<00:00,  6.42it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:30<00:00,  9.64it/s]
Perplexity: 100%|██████████| 164/164 [00:23<00:00,  6.85it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:17<00:00, 10.11it/s]
Perplexity: 100%|██████████| 164/164 [00:23<00:00,  7.11it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:17<00:00, 10.12it/s]
Perplexity: 100%|██████████| 164/164 [00:23<00:00,  7.12it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:06<00:00, 10.59it/s]
Perplexity: 100%|██████████| 164/164 [00:22<00:00,  7.42it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:06<00:00, 10.58it/s]
Perplexity: 100%|██████████| 164/164 [00:22<00:00,  7.44it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:06<00:00, 10.58it/s]
Perplexity: 100%|██████████| 164/164 [00:22<00:00,  7.41it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [03:32<00:00, 12.26it/s]
Perplexity: 100%|██████████| 164/164 [00:20<00:00,  8.19it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [03:50<00:00, 11.32it/s]
Perplexity: 100%|██████████| 164/164 [00:20<00:00,  7.83it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [03:50<00:00, 11.32it/s]
Perplexity: 100%|██████████| 164/164 [00:20<00:00,  7.83it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [03:04<00:00, 14.12it/s]
Perplexity: 100%|██████████| 164/164 [00:17<00:00,  9.37it/s]

[Full-heal QLoRA] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_full_heal_qlora.csv

,variant,percent,method,ppl_pre_qlora,ppl_post_qlora,adapters,ok,error
0,none,10,weighted_mean,11.563365,13.585173,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
1,tblock_blank_preheal,10,weighted_mean,12.194977,10.085325,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
2,tblock_avg_post_single_layer_heal,10,weighted_mean,9.806059,10.095195,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
3,none,20,weighted_mean,13.710756,11.611507,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
4,tblock_blank_preheal,20,weighted_mean,16.040251,13.181382,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
5,tblock_avg_post_single_layer_heal,20,weighted_mean,10.740537,13.138510,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
6,none,30,weighted_mean,17.134082,14.730461,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
7,tblock_blank_preheal,30,weighted_mean,19.716346,17.105916,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
8,tblock_avg_post_single_layer_heal,30,weighted_mean,11.711585,14.815254,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
9,none,40,weighted_mean,30.934981,16.829581,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
10,tblock_blank_preheal,40,weighted_mean,40.012594,17.718145,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
11,tblock_avg_post_single_layer_heal,40,weighted_mean,14.199038,18.504332,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
12,none,50,weighted_mean,71.840211,18.744520,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
13,tblock_blank_preheal,50,weighted_mean,167.876683,20.786972,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
14,tblock_avg_post_single_layer_heal,50,weighted_mean,20.986716,23.008777,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None

In [5]:
from transformers import BitsAndBytesConfig
from llm_layer_pruner import LLMLayerPruner
from dataset_builder import MixtureDataBuilder

# ---------------------------
# 1. Setup
# ---------------------------

# Load the model with 8-bit quantization
bnb_8bit = BitsAndBytesConfig(
    load_in_8bit=True,                    # int8 linear layers
)

# Load the model with 4-bit quantization
bnb_4bit = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",            # QLoRA default
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=(
        torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    ),
)

# Load the model
model_name = "Qwen/Qwen2.5-1.5B"
pruner = LLMLayerPruner(
    model_name=model_name,
    # quant_config=bnb_4bit,
    default_percentages=[10, 20], #, 30, 40, 50],
    default_rank=16,
    default_max_heal_steps=500,
    default_max_qlora_steps=1000,
    blank_noise_std=0.01,                 # small noise for the blank layer
)

pruner.configure_profiles(
    ppl=None,
    single_heal=bnb_8bit,
    qlora=bnb_4bit,
    max_eval_seq_len=512,
)

builder = MixtureDataBuilder(pruner.tokenizer, max_length=512, seed=42, verbose=True)

# Build separate Train/Val/Test mixtures with token budgets per domain:
token_targets_by_split = {
    "train": {"syntax": 20_000, "code": 20_000, "math": 20_000},
    "test":  {"syntax": 5_000, "code": 5_000, "math": 5_000},
}

texts_by_split, lengths_by_split, summary_by_split = builder.build_split_mixtures(
    token_targets_by_split,
    val_from_train_when_missing=True
)


# Make dataloaders (you can omit a split by leaving it out of token_targets_by_split)
loaders = builder.make_dataloaders_for_splits(
    texts_by_split,
    batch_sizes={ "train": 2, "test": 8},
    num_workers=4,
    pin_memory=True,
    shuffle=False,
)

train_dl = loaders["train"]
eval_dl = loaders["test"]


# Path to your analysis CSVs from earlier steps
agg_csvs = {
    "weighted_mean": f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_weighted_mean.csv",
    # "minimax":       f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_minimax.csv",
}

# ---------------------------
# 2. Pre-heal pruning sweep
# ---------------------------
df_pre = pruner.run_single_shot_pruning_sweep(
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    train_dataloader=train_dl,
    strategies=["none", "tblock_blank"], #, "tblock_avg", "tblock_lr_mean", "tblock_consensus"],
)
display(df_pre)

# ---------------------------
# 3. Single-layer heal sweep
# ---------------------------
df_heal = pruner.run_single_layer_heal_sweep(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    strategies=["tblock_blank", "tblock_avg"], #, "tblock_lr_mean", "tblock_consensus"],
    lr=2e-4,
    max_steps=350,
    grad_accum=4,
)
display(df_heal)

# ---------------------------
# 4. Full-model QLoRA healing experiments
# ---------------------------
df_full = pruner.run_full_heal_experiments(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    qlora_lr=1e-4,
    max_qlora_steps=700,
    grad_accum=4,
)
display(df_full)

/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[Mixture] Fallback for domain 'code': requested 'test' but using 'train'
[Mixture] Built 'test': domains={'syntax': 5081, 'code': 5326, 'math': 5010} | used_splits={'syntax': 'test', 'code': 'train', 'math': 'test'}
[Mixture] Built 'train': domains={'syntax': 20018, 'code': 20158, 'math': 20000} | used_splits={'syntax': 'train', 'code': 'train', 'math': 'train'}

Perplexity: 100%|██████████| 17/17 [00:01<00:00,  8.64it/s]

Baseline PPL: 12.176 (layers=28, hidden=1536)

Perplexity: 100%|██████████| 17/17 [00:01<00:00,  9.23it/s]
Perplexity: 100%|██████████| 17/17 [00:01<00:00,  9.32it/s]
Perplexity: 100%|██████████| 17/17 [00:01<00:00,  9.93it/s]
Perplexity: 100%|██████████| 17/17 [00:01<00:00,  9.94it/s]

[Pre-heal sweep] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_preheal_sweep.csv

,method,strategy,percent,selected_start,selected_end_inclusive,baseline_ppl,post_ppl,delta_ppl,inserted_idx,rank
0,weighted_mean,none,10,13,15,12.175613,11.489751,-0.685862,NaN,16
1,weighted_mean,tblock_blank,10,12,15,12.175613,12.251654,0.076041,12.0,16
2,weighted_mean,none,20,11,16,12.175613,13.919271,1.743658,NaN,16
3,weighted_mean,tblock_blank,20,9,15,12.175613,16.340384,4.164771,9.0,16

Heal@layer12: 100%|██████████| 265/265 [00:21<00:00, 12.18it/s]
Perplexity: 100%|██████████| 17/17 [00:01<00:00,  9.31it/s]

UnboundLocalError: cannot access local variable 'm' where it is not associated with a value

In [5]:
from transformers import BitsAndBytesConfig
from llm_layer_pruner import LLMLayerPruner
from dataset_builder import MixtureDataBuilder

# ---------------------------
# 1. Setup
# ---------------------------

# Load the model with 8-bit quantization
bnb_8bit = BitsAndBytesConfig(
    load_in_8bit=True,                    # int8 linear layers
)

# Load the model with 4-bit quantization
bnb_4bit = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",            # QLoRA default
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=(
        torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    ),
)

# Load the model
model_name = "Qwen/Qwen2.5-1.5B"
pruner = LLMLayerPruner(
    model_name=model_name,
    # quant_config=bnb_4bit,
    default_percentages=[10, 20, 30, 40, 50],
    default_rank=16,
    default_max_heal_steps=500,
    default_max_qlora_steps=1000,
    blank_noise_std=0.01,                 # small noise for the blank layer
)

pruner.configure_profiles(
    ppl=None,
    single_heal=bnb_8bit,
    qlora=bnb_4bit,
    max_eval_seq_len=512,
)

builder = MixtureDataBuilder(pruner.tokenizer, max_length=512, seed=42, verbose=True)

# Build separate Train/Val/Test mixtures with token budgets per domain:
token_targets_by_split = {
    "train": {"syntax": 200_000, "code": 200_000, "math": 200_000},
    "test":  {"syntax": 50_000, "code": 50_000, "math": 50_000},
}

texts_by_split, lengths_by_split, summary_by_split = builder.build_split_mixtures(
    token_targets_by_split,
    val_from_train_when_missing=True
)


# Make dataloaders (you can omit a split by leaving it out of token_targets_by_split)
loaders = builder.make_dataloaders_for_splits(
    texts_by_split,
    batch_sizes={ "train": 2, "test": 8},
    num_workers=4,
    pin_memory=True,
    shuffle=False,
)

train_dl = loaders["train"]
eval_dl = loaders["test"]


# Path to your analysis CSVs from earlier steps
agg_csvs = {
    "weighted_mean": f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_weighted_mean.csv",
    # "minimax":       f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_minimax.csv",
}

# ---------------------------
# 2. Pre-heal pruning sweep
# ---------------------------
df_pre = pruner.run_single_shot_pruning_sweep(
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    train_dataloader=train_dl,
    strategies=["none", "tblock_blank", "tblock_avg", "tblock_lr_mean", "tblock_consensus"],
)
display(df_pre)

# ---------------------------
# 3. Single-layer heal sweep
# ---------------------------
df_heal = pruner.run_single_layer_heal_sweep(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    strategies=["tblock_blank", "tblock_avg", "tblock_lr_mean", "tblock_consensus"],
    lr=2e-4,
    max_steps=350,
    grad_accum=4,
)
display(df_heal)

# ---------------------------
# 4. Full-model QLoRA healing experiments
# ---------------------------
df_full = pruner.run_full_heal_experiments(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    qlora_lr=1e-4,
    max_qlora_steps=700,
    grad_accum=4,
)
display(df_full)

/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[Mixture] Fallback for domain 'code': requested 'test' but using 'train'
[Mixture] Built 'test': domains={'syntax': 50374, 'code': 50084, 'math': 50032} | used_splits={'syntax': 'test', 'code': 'train', 'math': 'test'}
[Mixture] Built 'train': domains={'syntax': 200046, 'code': 200126, 'math': 200034} | used_splits={'syntax': 'train', 'code': 'train', 'math': 'train'}

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 13.67it/s]

Baseline PPL: 12.409 (layers=28, hidden=1536)

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.22it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.18it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.12it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.08it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.10it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.08it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.03it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.04it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.85it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.79it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 18.05it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 18.05it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 18.03it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 18.04it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 18.08it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 19.60it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 20.26it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 20.23it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 20.24it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 20.24it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 23.07it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 23.01it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 23.05it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 22.99it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 22.57it/s]

[Pre-heal sweep] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_preheal_sweep.csv

,method,strategy,percent,selected_start,selected_end_inclusive,baseline_ppl,post_ppl,delta_ppl,inserted_idx,rank
0,weighted_mean,none,10,13,15,12.408719,11.563365,-0.845354,NaN,16
1,weighted_mean,tblock_blank,10,12,15,12.408719,12.192314,-0.216405,12.0,16
2,weighted_mean,tblock_avg,10,12,15,12.408719,12.123243,-0.285476,12.0,16
3,weighted_mean,tblock_lr_mean,10,12,15,12.408719,12.252200,-0.156519,12.0,16
4,weighted_mean,tblock_consensus,10,12,15,12.408719,12.221641,-0.187079,12.0,16
5,weighted_mean,none,20,11,16,12.408719,13.710756,1.302037,NaN,16
6,weighted_mean,tblock_blank,20,9,15,12.408719,16.041728,3.633009,9.0,16
7,weighted_mean,tblock_avg,20,9,15,12.408719,15.765839,3.357119,9.0,16
8,weighted_mean,tblock_lr_mean,20,9,15,12.408719,16.073602,3.664883,9.0,16
9,weighted_mean,tblock_consensus,20,9,15,12.408719,16.051596,3.642877,9.0,16
10,weighted_mean,none,30,9,16,12.408719,17.134082,4.725363,NaN,16
11,weighted_mean,tblock_blank,30,8,16,12.408719,19.715064,7.306345,8.0,16
12,weighted_mean,tblock_avg,30,8,16,12.408719,19.411582,7.002863,8.0,16
13,weighted_mean,tblock_lr_mean,30,8,16,12.408719,19.733177,7.324457,8.0,16
14,weighted_mean,tblock_consensus,30,8,16,12.408719,19.720212,7.311493,8.0,16
15,weighted_mean,none,40,8,18,12.408719,30.934981,18.526262,NaN,16
16,weighted_mean,tblock_blank,40,7,18,12.408719,40.018155,27.609436,7.0,16
17,weighted_mean,tblock_avg,40,7,18,12.408719,39.055418,26.646699,7.0,16
18,weighted_mean,tblock_lr_mean,40,7,18,12.408719,40.035429,27.626710,7.0,16
19,weighted_mean,tblock_consensus,40,7,18,12.408719,40.033488,27.624769,7.0,16
20,weighted_mean,none,50,7,20,12.408719,71.840211,59.431492,NaN,16
21,weighted_mean,tblock_blank,50,7,21,12.408719,167.938660,155.529941,7.0,16
22,weighted_mean,tblock_avg,50,7,21,12.408719,161.515002,149.106283,7.0,16
23,weighted_mean,tblock_lr_mean,50,7,21,12.408719,167.149121,154.740401,7.0,16
24,weighted_mean,tblock_consensus,50,7,21,12.408719,167.877872,155.469153,7.0,16

Heal@layer12:  54%|█████▎    | 1399/2607 [02:17<01:58, 10.16it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.56it/s]
Heal@layer12:  54%|█████▎    | 1399/2607 [02:18<01:59, 10.10it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.66it/s]
Heal@layer12:  18%|█▊        | 479/2607 [01:09<05:10,  6.84it/s]

KeyboardInterrupt:

In [5]:
from transformers import BitsAndBytesConfig
from llm_layer_pruner import LLMLayerPruner
from dataset_builder import MixtureDataBuilder

# ---------------------------
# 1. Setup
# ---------------------------

# Load the model with 8-bit quantization
bnb_8bit = BitsAndBytesConfig(
    load_in_8bit=True,                    # int8 linear layers
)

# Load the model with 4-bit quantization
bnb_4bit = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",            # QLoRA default
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=(
        torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    ),
)

# Load the model
model_name = "Qwen/Qwen2.5-1.5B"
pruner = LLMLayerPruner(
    model_name=model_name,
    # quant_config=bnb_4bit,
    default_percentages=[10, 20], #, 30, 40, 50],
    default_rank=16,
    default_max_heal_steps=500,
    default_max_qlora_steps=1000,
    blank_noise_std=0.01,                 # small noise for the blank layer
)

pruner.configure_profiles(
    ppl=None,
    single_heal=None,
    qlora=None,
    max_eval_seq_len=512,
)

builder = MixtureDataBuilder(pruner.tokenizer, max_length=512, seed=42, verbose=True)

# Build separate Train/Val/Test mixtures with token budgets per domain:
token_targets_by_split = {
    "train": {"syntax": 200_000, "code": 200_000, "math": 200_000},
    "test":  {"syntax": 50_000, "code": 50_000, "math": 50_000},
}

texts_by_split, lengths_by_split, summary_by_split = builder.build_split_mixtures(
    token_targets_by_split,
    val_from_train_when_missing=True
)


# Make dataloaders (you can omit a split by leaving it out of token_targets_by_split)
loaders = builder.make_dataloaders_for_splits(
    texts_by_split,
    batch_sizes={ "train": 2, "test": 8},
    num_workers=4,
    pin_memory=True,
    shuffle=False,
)

train_dl = loaders["train"]
eval_dl = loaders["test"]


# Path to your analysis CSVs from earlier steps
agg_csvs = {
    "weighted_mean": f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_weighted_mean.csv",
    # "minimax":       f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_minimax.csv",
}

# ---------------------------
# 2. Pre-heal pruning sweep
# ---------------------------
df_pre = pruner.run_single_shot_pruning_sweep(
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    train_dataloader=train_dl,
    strategies=["none", "tblock_blank", "tblock_avg"], #, "tblock_lr_mean", "tblock_consensus"],
)
display(df_pre)

# ---------------------------
# 3. Single-layer heal sweep
# ---------------------------
df_heal = pruner.run_single_layer_heal_sweep(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    strategies=["tblock_blank", "tblock_avg"], #, "tblock_lr_mean", "tblock_consensus"],
    lr=2e-4,
    max_steps=350,
    grad_accum=4,
)
display(df_heal)

# ---------------------------
# 4. Full-model QLoRA healing experiments
# ---------------------------
df_full = pruner.run_full_heal_experiments(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    qlora_lr=1e-4,
    max_qlora_steps=700,
    grad_accum=4,
)
display(df_full)

/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[Mixture] Fallback for domain 'code': requested 'test' but using 'train'
[Mixture] Built 'test': domains={'syntax': 50374, 'code': 50084, 'math': 50032} | used_splits={'syntax': 'test', 'code': 'train', 'math': 'test'}
[Mixture] Built 'train': domains={'syntax': 200046, 'code': 200126, 'math': 200034} | used_splits={'syntax': 'train', 'code': 'train', 'math': 'train'}

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 13.52it/s]

Baseline PPL: 12.409 (layers=28, hidden=1536)

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.00it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 14.95it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.89it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.85it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.81it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.84it/s]

[Pre-heal sweep] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_preheal_sweep.csv

,method,strategy,percent,selected_start,selected_end_inclusive,baseline_ppl,post_ppl,delta_ppl,inserted_idx,rank
0,weighted_mean,none,10,13,15,12.408719,11.563365,-0.845354,NaN,16
1,weighted_mean,tblock_blank,10,12,15,12.408719,12.193295,-0.215424,12.0,16
2,weighted_mean,tblock_avg,10,12,15,12.408719,12.123243,-0.285476,12.0,16
3,weighted_mean,none,20,11,16,12.408719,13.710756,1.302037,NaN,16
4,weighted_mean,tblock_blank,20,9,15,12.408719,16.040329,3.631610,9.0,16
5,weighted_mean,tblock_avg,20,9,15,12.408719,15.765839,3.357119,9.0,16

Heal@layer12:  54%|█████▎    | 1399/2607 [02:13<01:54, 10.51it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.79it/s]
Heal@layer12:  54%|█████▎    | 1399/2607 [02:16<01:57, 10.24it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.81it/s]
Heal@layer9:  54%|█████▎    | 1399/2607 [02:13<01:55, 10.49it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.48it/s]
Heal@layer9:  54%|█████▎    | 1399/2607 [02:13<01:55, 10.49it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.45it/s]

[Single-layer heal] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_single_layer_heal.csv

,method,strategy,percent,selected_start,selected_end_inclusive,ppl_before_heal,ppl_after_heal,delta_ppl,inserted_idx,rank
0,weighted_mean,tblock_blank,10,12,15,12.193295,10.342245,-1.851050,12,16
1,weighted_mean,tblock_avg,10,12,15,12.123243,9.812681,-2.310562,12,16
2,weighted_mean,tblock_blank,20,9,15,16.040329,11.409420,-4.630910,9,16
3,weighted_mean,tblock_avg,20,9,15,15.765839,10.740783,-5.025055,9,16

QLoRA-heal: 100%|██████████| 2607/2607 [05:25<00:00,  8.02it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.93it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [05:21<00:00,  8.12it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.85it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [05:25<00:00,  8.01it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.04it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:54<00:00,  8.86it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.12it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:44<00:00,  9.16it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.91it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:57<00:00,  8.77it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.43it/s]

[Full-heal QLoRA] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_full_heal_qlora.csv

,variant,percent,method,ppl_pre_qlora,ppl_post_qlora,adapters,ok,error
0,none,10,weighted_mean,11.563365,9.777906,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
1,tblock_blank_preheal,10,weighted_mean,12.193295,10.452549,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
2,tblock_avg_post_single_layer_heal,10,weighted_mean,9.812681,10.472776,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
3,none,20,weighted_mean,13.710756,12.858397,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
4,tblock_blank_preheal,20,weighted_mean,16.040329,15.154206,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
5,tblock_avg_post_single_layer_heal,20,weighted_mean,10.740783,14.289465,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None

In [5]:
from transformers import BitsAndBytesConfig
from llm_layer_pruner import LLMLayerPruner
from dataset_builder import MixtureDataBuilder

# ---------------------------
# 1. Setup
# ---------------------------

# Load the model with 8-bit quantization
bnb_8bit = BitsAndBytesConfig(
    load_in_8bit=True,                    # int8 linear layers
)

# Load the model with 4-bit quantization
bnb_4bit = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",            # QLoRA default
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=(
        torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    ),
)

# Load the model
model_name = "Qwen/Qwen2.5-1.5B"
pruner = LLMLayerPruner(
    model_name=model_name,
    # quant_config=bnb_4bit,
    default_percentages=[10, 20], #, 30, 40, 50],
    default_rank=16,
    default_max_heal_steps=500,
    default_max_qlora_steps=1000,
    blank_noise_std=0.01,                 # small noise for the blank layer
)

pruner.configure_profiles(
    ppl=None,
    single_heal=None,
    qlora=None,
    max_eval_seq_len=512,
)

builder = MixtureDataBuilder(pruner.tokenizer, max_length=512, seed=42, verbose=True)

# Build separate Train/Val/Test mixtures with token budgets per domain:
token_targets_by_split = {
    "train": {"syntax": 200_000, "code": 200_000, "math": 200_000},
    "test":  {"syntax": 50_000, "code": 50_000, "math": 50_000},
}

texts_by_split, lengths_by_split, summary_by_split = builder.build_split_mixtures(
    token_targets_by_split,
    val_from_train_when_missing=True
)


# Make dataloaders (you can omit a split by leaving it out of token_targets_by_split)
loaders = builder.make_dataloaders_for_splits(
    texts_by_split,
    batch_sizes={ "train": 2, "test": 8},
    num_workers=4,
    pin_memory=True,
    shuffle=False,
)

train_dl = loaders["train"]
eval_dl = loaders["test"]


# Path to your analysis CSVs from earlier steps
agg_csvs = {
    "weighted_mean": f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_weighted_mean.csv",
    # "minimax":       f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_minimax.csv",
}

# ---------------------------
# 2. Pre-heal pruning sweep
# ---------------------------
df_pre = pruner.run_single_shot_pruning_sweep(
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    train_dataloader=train_dl,
    strategies=["none", "tblock_blank", "tblock_avg"], #, "tblock_lr_mean", "tblock_consensus"],
)
display(df_pre)

# ---------------------------
# 3. Single-layer heal sweep
# ---------------------------
df_heal = pruner.run_single_layer_heal_sweep(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    strategies=["tblock_blank", "tblock_avg"], #, "tblock_lr_mean", "tblock_consensus"],
    lr=2e-4,
    max_steps=350,
    grad_accum=4,
)
display(df_heal)

# ---------------------------
# 4. Full-model QLoRA healing experiments
# ---------------------------
df_full = pruner.run_full_heal_experiments(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    qlora_lr=1e-4,
    max_qlora_steps=700,
    grad_accum=4,
)
display(df_full)

/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[Mixture] Fallback for domain 'code': requested 'test' but using 'train'
[Mixture] Built 'test': domains={'syntax': 50374, 'code': 50084, 'math': 50032} | used_splits={'syntax': 'test', 'code': 'train', 'math': 'test'}
[Mixture] Built 'train': domains={'syntax': 200046, 'code': 200126, 'math': 200034} | used_splits={'syntax': 'train', 'code': 'train', 'math': 'train'}

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 13.42it/s]

Baseline PPL: 12.409 (layers=28, hidden=1536)

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 14.94it/s]
Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.01it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.48it/s]
Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.82it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.83it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.82it/s]

[Pre-heal sweep] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_preheal_sweep.csv

,method,strategy,percent,selected_start,selected_end_inclusive,baseline_ppl,post_ppl,delta_ppl,inserted_idx,rank
0,weighted_mean,none,10,13,15,12.408719,11.563365,-0.845354,NaN,16
1,weighted_mean,tblock_blank,10,12,15,12.408719,12.195708,-0.213011,12.0,16
2,weighted_mean,tblock_avg,10,12,15,12.408719,12.123243,-0.285476,12.0,16
3,weighted_mean,none,20,11,16,12.408719,13.710756,1.302037,NaN,16
4,weighted_mean,tblock_blank,20,9,15,12.408719,16.039675,3.630956,9.0,16
5,weighted_mean,tblock_avg,20,9,15,12.408719,15.765839,3.357119,9.0,16

Heal@layer12:  54%|█████▎    | 1399/2607 [01:21<01:09, 17.26it/s]
Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.90it/s]
Heal@layer12:  54%|█████▎    | 1399/2607 [01:18<01:08, 17.73it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.18it/s]
Heal@layer9:  54%|█████▎    | 1399/2607 [01:17<01:06, 18.07it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.67it/s]
Heal@layer9:  54%|█████▎    | 1399/2607 [01:17<01:07, 18.03it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.63it/s]

[Single-layer heal] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_single_layer_heal.csv

,method,strategy,percent,selected_start,selected_end_inclusive,ppl_before_heal,ppl_after_heal,delta_ppl,inserted_idx,rank
0,weighted_mean,tblock_blank,10,12,15,12.195708,10.138438,-2.057270,12,16
1,weighted_mean,tblock_avg,10,12,15,12.123243,9.801807,-2.321435,12,16
2,weighted_mean,tblock_blank,20,9,15,16.039675,11.351434,-4.688241,9,16
3,weighted_mean,tblock_avg,20,9,15,15.765839,10.749293,-5.016546,9,16

QLoRA-heal: 100%|██████████| 2607/2607 [05:25<00:00,  8.00it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.10it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [05:27<00:00,  7.96it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.17it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [05:25<00:00,  8.01it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.05it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:54<00:00,  8.86it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.86it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [04:59<00:00,  8.72it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.28it/s]
QLoRA-heal: 100%|██████████| 2607/2607 [05:03<00:00,  8.58it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.28it/s]

[Full-heal QLoRA] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_full_heal_qlora.csv

,variant,percent,method,ppl_pre_qlora,ppl_post_qlora,adapters,ok,error
0,none,10,weighted_mean,11.563365,9.883399,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
1,tblock_blank_preheal,10,weighted_mean,12.195708,10.461172,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
2,tblock_avg_post_single_layer_heal,10,weighted_mean,9.801807,10.405285,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
3,none,20,weighted_mean,13.710756,12.901056,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
4,tblock_blank_preheal,20,weighted_mean,16.039675,14.358333,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
5,tblock_avg_post_single_layer_heal,20,weighted_mean,10.749293,14.199004,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None

In [5]:
from transformers import BitsAndBytesConfig
from llm_layer_pruner import LLMLayerPruner
from dataset_builder import MixtureDataBuilder

# ---------------------------
# 1. Setup
# ---------------------------

# Load the model with 8-bit quantization
bnb_8bit = BitsAndBytesConfig(
    load_in_8bit=True,                    # int8 linear layers
)

# Load the model with 4-bit quantization
bnb_4bit = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",            # QLoRA default
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=(
        torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    ),
)

# Load the model
model_name = "Qwen/Qwen2.5-1.5B"
pruner = LLMLayerPruner(
    model_name=model_name,
    # quant_config=bnb_4bit,
    default_percentages=[10, 20], #, 30, 40, 50],
    default_rank=16,
    default_max_heal_steps=500,
    default_max_qlora_steps=1000,
    blank_noise_std=0.01,                 # small noise for the blank layer
)

pruner.configure_profiles(
    ppl=None,
    single_heal=None,
    qlora=None,
    max_eval_seq_len=512,
)

builder = MixtureDataBuilder(pruner.tokenizer, max_length=512, seed=42, verbose=True)

# Build separate Train/Val/Test mixtures with token budgets per domain:
token_targets_by_split = {
    "train": {"syntax": 200_000, "code": 200_000, "math": 200_000},
    "test":  {"syntax": 50_000, "code": 50_000, "math": 50_000},
}

texts_by_split, lengths_by_split, summary_by_split = builder.build_split_mixtures(
    token_targets_by_split,
    val_from_train_when_missing=True
)


# Make dataloaders (you can omit a split by leaving it out of token_targets_by_split)
loaders = builder.make_dataloaders_for_splits(
    texts_by_split,
    batch_sizes={ "train": 2, "test": 8},
    num_workers=4,
    pin_memory=True,
    shuffle=False,
)

train_dl = loaders["train"]
eval_dl = loaders["test"]


# Path to your analysis CSVs from earlier steps
agg_csvs = {
    "weighted_mean": f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_weighted_mean.csv",
    # "minimax":       f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_minimax.csv",
}

# ---------------------------
# 2. Pre-heal pruning sweep
# ---------------------------
df_pre = pruner.run_single_shot_pruning_sweep(
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    train_dataloader=train_dl,
    strategies=["none", "tblock_blank", "tblock_avg"], #, "tblock_lr_mean", "tblock_consensus"],
)
display(df_pre)

# ---------------------------
# 3. Single-layer heal sweep
# ---------------------------
df_heal = pruner.run_single_layer_heal_sweep(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    strategies=["tblock_blank", "tblock_avg"], #, "tblock_lr_mean", "tblock_consensus"],
    lr=2e-4,
    max_steps=350,
    grad_accum=4,
)
display(df_heal)

# ---------------------------
# 4. Full-model QLoRA healing experiments
# ---------------------------
df_full = pruner.run_full_heal_experiments(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    qlora_lr=1e-4,
    max_qlora_steps=700,
    grad_accum=4,
)
display(df_full)

/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[Mixture] Fallback for domain 'code': requested 'test' but using 'train'
[Mixture] Built 'test': domains={'syntax': 50374, 'code': 50084, 'math': 50032} | used_splits={'syntax': 'test', 'code': 'train', 'math': 'test'}
[Mixture] Built 'train': domains={'syntax': 200046, 'code': 200126, 'math': 200034} | used_splits={'syntax': 'train', 'code': 'train', 'math': 'train'}

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 13.17it/s]

Baseline PPL: 12.409 (layers=28, hidden=1536)

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.66it/s]
Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.66it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.55it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.56it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.50it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.42it/s]

[Pre-heal sweep] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_preheal_sweep.csv

,method,strategy,percent,selected_start,selected_end_inclusive,baseline_ppl,post_ppl,delta_ppl,inserted_idx,rank
0,weighted_mean,none,10,13,15,12.408719,11.563365,-0.845354,NaN,16
1,weighted_mean,tblock_blank,10,12,15,12.408719,12.193661,-0.215058,12.0,16
2,weighted_mean,tblock_avg,10,12,15,12.408719,12.123243,-0.285476,12.0,16
3,weighted_mean,none,20,11,16,12.408719,13.710756,1.302037,NaN,16
4,weighted_mean,tblock_blank,20,9,15,12.408719,16.039405,3.630686,9.0,16
5,weighted_mean,tblock_avg,20,9,15,12.408719,15.765839,3.357119,9.0,16

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 12.97it/s]

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 12.65it/s]

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.06it/s]

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.52it/s]

[Single-layer heal] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_single_layer_heal.csv

,method,strategy,percent,selected_start,selected_end_inclusive,ppl_before_heal,ppl_after_heal,delta_ppl,inserted_idx,rank
0,weighted_mean,tblock_blank,10,12,15,12.193661,10.047106,-2.146555,12,16
1,weighted_mean,tblock_avg,10,12,15,12.123243,10.041613,-2.081630,12,16
2,weighted_mean,tblock_blank,20,9,15,16.039405,11.622125,-4.417280,9,16
3,weighted_mean,tblock_avg,20,9,15,15.765839,11.498200,-4.267639,9,16

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

RuntimeError: The size of tensor a (12) must match the size of tensor b (2) at non-singleton dimension 3

In [5]:
from transformers import BitsAndBytesConfig
from llm_layer_pruner import LLMLayerPruner
from dataset_builder import MixtureDataBuilder

# ---------------------------
# 1. Setup
# ---------------------------

# Load the model with 8-bit quantization
bnb_8bit = BitsAndBytesConfig(
    load_in_8bit=True,                    # int8 linear layers
)

# Load the model with 4-bit quantization
bnb_4bit = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",            # QLoRA default
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=(
        torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    ),
)

# Load the model
model_name = "Qwen/Qwen2.5-1.5B"
pruner = LLMLayerPruner(
    model_name=model_name,
    # quant_config=bnb_4bit,
    default_percentages=[10, 20, 30, 40, 50],
    default_rank=16,
    default_max_heal_steps=500,
    default_max_qlora_steps=1000,
    blank_noise_std=0.01,                 # small noise for the blank layer
)

pruner.configure_profiles(
    ppl=None,
    single_heal=None,
    qlora=None,
    max_eval_seq_len=512,
)

builder = MixtureDataBuilder(pruner.tokenizer, max_length=512, seed=42, verbose=True)

# Build separate Train/Val/Test mixtures with token budgets per domain:
token_targets_by_split = {
    "train": {"syntax": 200_000, "code": 200_000, "math": 200_000},
    "test":  {"syntax": 50_000, "code": 50_000, "math": 50_000},
}

texts_by_split, lengths_by_split, summary_by_split = builder.build_split_mixtures(
    token_targets_by_split,
    val_from_train_when_missing=True
)


# Make dataloaders (you can omit a split by leaving it out of token_targets_by_split)
loaders = builder.make_dataloaders_for_splits(
    texts_by_split,
    batch_sizes={ "train": 2, "test": 8},
    num_workers=4,
    pin_memory=True,
    shuffle=False,
)

train_dl = loaders["train"]
eval_dl = loaders["test"]


# Path to your analysis CSVs from earlier steps
agg_csvs = {
    "weighted_mean": f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_weighted_mean.csv",
    # "minimax":       f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_minimax.csv",
}

# ---------------------------
# 2. Pre-heal pruning sweep
# ---------------------------
df_pre = pruner.run_single_shot_pruning_sweep(
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    train_dataloader=train_dl,
    strategies=["none", "tblock_blank", "tblock_avg", "tblock_lr_mean", "tblock_consensus"],
)
display(df_pre)

# ---------------------------
# 3. Single-layer heal sweep
# ---------------------------
df_heal = pruner.run_single_layer_heal_sweep(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    strategies=["tblock_blank", "tblock_avg", "tblock_lr_mean", "tblock_consensus"],
    lr=2e-4,
    max_steps=350,
    grad_accum=4,
)
display(df_heal)

# ---------------------------
# 4. Full-model QLoRA healing experiments
# ---------------------------
df_full = pruner.run_full_heal_experiments(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    qlora_lr=1e-4,
    max_qlora_steps=700,
    grad_accum=4,
)
display(df_full)

/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[Mixture] Fallback for domain 'code': requested 'test' but using 'train'
[Mixture] Built 'test': domains={'syntax': 50374, 'code': 50084, 'math': 50032} | used_splits={'syntax': 'test', 'code': 'train', 'math': 'test'}
[Mixture] Built 'train': domains={'syntax': 200046, 'code': 200126, 'math': 200034} | used_splits={'syntax': 'train', 'code': 'train', 'math': 'train'}

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 13.77it/s]

Baseline PPL: 12.409 (layers=28, hidden=1536)

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.38it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.33it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.29it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.28it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 16.27it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.27it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.22it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.17it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.21it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.22it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.45it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.44it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.50it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.49it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.56it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 20.03it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 20.78it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 20.73it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 20.73it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 20.80it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 23.72it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 23.65it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 23.70it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 23.66it/s]
Perplexity: 100%|██████████| 164/164 [00:06<00:00, 23.74it/s]

[Pre-heal sweep] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_preheal_sweep.csv

,method,strategy,percent,selected_start,selected_end_inclusive,baseline_ppl,post_ppl,delta_ppl,inserted_idx,rank
0,weighted_mean,none,10,13,15,12.408719,11.563365,-0.845354,NaN,16
1,weighted_mean,tblock_blank,10,12,15,12.408719,12.194480,-0.214239,12.0,16
2,weighted_mean,tblock_avg,10,12,15,12.408719,12.123243,-0.285476,12.0,16
3,weighted_mean,tblock_lr_mean,10,12,15,12.408719,12.252200,-0.156519,12.0,16
4,weighted_mean,tblock_consensus,10,12,15,12.408719,12.221641,-0.187079,12.0,16
5,weighted_mean,none,20,11,16,12.408719,13.710756,1.302037,NaN,16
6,weighted_mean,tblock_blank,20,9,15,12.408719,16.037348,3.628629,9.0,16
7,weighted_mean,tblock_avg,20,9,15,12.408719,15.765839,3.357119,9.0,16
8,weighted_mean,tblock_lr_mean,20,9,15,12.408719,16.073602,3.664883,9.0,16
9,weighted_mean,tblock_consensus,20,9,15,12.408719,16.051596,3.642877,9.0,16
10,weighted_mean,none,30,9,16,12.408719,17.134082,4.725363,NaN,16
11,weighted_mean,tblock_blank,30,8,16,12.408719,19.714467,7.305748,8.0,16
12,weighted_mean,tblock_avg,30,8,16,12.408719,19.411582,7.002863,8.0,16
13,weighted_mean,tblock_lr_mean,30,8,16,12.408719,19.733177,7.324457,8.0,16
14,weighted_mean,tblock_consensus,30,8,16,12.408719,19.720212,7.311493,8.0,16
15,weighted_mean,none,40,8,18,12.408719,30.934981,18.526262,NaN,16
16,weighted_mean,tblock_blank,40,7,18,12.408719,40.020047,27.611327,7.0,16
17,weighted_mean,tblock_avg,40,7,18,12.408719,39.055418,26.646699,7.0,16
18,weighted_mean,tblock_lr_mean,40,7,18,12.408719,40.035429,27.626710,7.0,16
19,weighted_mean,tblock_consensus,40,7,18,12.408719,40.033488,27.624769,7.0,16
20,weighted_mean,none,50,7,20,12.408719,71.840211,59.431492,NaN,16
21,weighted_mean,tblock_blank,50,7,21,12.408719,167.871553,155.462834,7.0,16
22,weighted_mean,tblock_avg,50,7,21,12.408719,161.515002,149.106283,7.0,16
23,weighted_mean,tblock_lr_mean,50,7,21,12.408719,167.149121,154.740401,7.0,16
24,weighted_mean,tblock_consensus,50,7,21,12.408719,167.877872,155.469153,7.0,16

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.44it/s]

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 13.33it/s]

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.19it/s]

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 13.07it/s]

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.43it/s]

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 13.94it/s]

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.32it/s]

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.00it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.03it/s]

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.75it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.01it/s]

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.75it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.98it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.29it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.67it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.66it/s]

Perplexity: 100%|██████████| 164/164 [00:08<00:00, 19.34it/s]

Perplexity: 100%|██████████| 164/164 [00:08<00:00, 19.32it/s]

Perplexity: 100%|██████████| 164/164 [00:08<00:00, 19.30it/s]

Perplexity: 100%|██████████| 164/164 [00:08<00:00, 19.27it/s]

[Single-layer heal] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_single_layer_heal.csv

,method,strategy,percent,selected_start,selected_end_inclusive,ppl_before_heal,ppl_after_heal,delta_ppl,inserted_idx,rank
0,weighted_mean,tblock_blank,10,12,15,12.194480,10.052920,-2.141560,12,16
1,weighted_mean,tblock_avg,10,12,15,12.123243,10.037393,-2.085850,12,16
2,weighted_mean,tblock_lr_mean,10,12,15,12.252200,10.069634,-2.182566,12,16
3,weighted_mean,tblock_consensus,10,12,15,12.221641,10.117489,-2.104151,12,16
4,weighted_mean,tblock_blank,20,9,15,16.037348,11.606817,-4.430531,9,16
5,weighted_mean,tblock_avg,20,9,15,15.765839,11.498158,-4.267680,9,16
6,weighted_mean,tblock_lr_mean,20,9,15,16.073602,11.640553,-4.433049,9,16
7,weighted_mean,tblock_consensus,20,9,15,16.051596,11.796865,-4.254732,9,16
8,weighted_mean,tblock_blank,30,8,16,19.714467,13.200445,-6.514022,8,16
9,weighted_mean,tblock_avg,30,8,16,19.411582,12.945672,-6.465910,8,16
10,weighted_mean,tblock_lr_mean,30,8,16,19.733177,13.133219,-6.599957,8,16
11,weighted_mean,tblock_consensus,30,8,16,19.720212,13.379061,-6.341151,8,16
12,weighted_mean,tblock_blank,40,7,18,40.020047,17.298455,-22.721592,7,16
13,weighted_mean,tblock_avg,40,7,18,39.055418,17.035244,-22.020174,7,16
14,weighted_mean,tblock_lr_mean,40,7,18,40.035429,17.934887,-22.100542,7,16
15,weighted_mean,tblock_consensus,40,7,18,40.033488,18.324503,-21.708986,7,16
16,weighted_mean,tblock_blank,50,7,21,167.871553,31.411834,-136.459719,7,16
17,weighted_mean,tblock_avg,50,7,21,161.515002,30.367132,-131.147870,7,16
18,weighted_mean,tblock_lr_mean,50,7,21,167.149121,32.346299,-134.802822,7,16
19,weighted_mean,tblock_consensus,50,7,21,167.877872,33.491948,-134.385924,7,16

Perplexity: 100%|██████████| 164/164 [00:13<00:00, 11.89it/s]

Perplexity: 100%|██████████| 164/164 [00:13<00:00, 11.97it/s]

Perplexity: 100%|██████████| 164/164 [00:13<00:00, 11.92it/s]

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 12.74it/s]

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 12.65it/s]

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 12.92it/s]

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 13.42it/s]

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 13.71it/s]

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 13.69it/s]

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.49it/s]

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.05it/s]

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 14.98it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.32it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.72it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.26it/s]

[Full-heal QLoRA] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_full_heal_qlora.csv

,variant,percent,method,ppl_pre_qlora,ppl_post_qlora,adapters,ok,error
0,none,10,weighted_mean,11.563365,9.307076,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
1,tblock_blank_preheal,10,weighted_mean,12.194480,9.413632,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
2,tblock_avg_post_single_layer_heal,10,weighted_mean,10.037393,9.399608,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
3,none,20,weighted_mean,13.710756,10.013897,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
4,tblock_blank_preheal,20,weighted_mean,16.037348,10.503818,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
5,tblock_avg_post_single_layer_heal,20,weighted_mean,11.498158,10.456890,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
6,none,30,weighted_mean,17.134082,10.939887,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
7,tblock_blank_preheal,30,weighted_mean,19.714467,11.642281,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
8,tblock_avg_post_single_layer_heal,30,weighted_mean,12.945672,11.671425,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
9,none,40,weighted_mean,30.934981,13.231048,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
10,tblock_blank_preheal,40,weighted_mean,40.020047,14.463851,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
11,tblock_avg_post_single_layer_heal,40,weighted_mean,17.035244,14.351261,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
12,none,50,weighted_mean,71.840211,19.141662,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
13,tblock_blank_preheal,50,weighted_mean,167.871553,22.618061,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
14,tblock_avg_post_single_layer_heal,50,weighted_mean,30.367132,22.461190,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None

In [5]:
from transformers import BitsAndBytesConfig
from llm_layer_pruner import LLMLayerPruner
from dataset_builder import MixtureDataBuilder

# ---------------------------
# 1. Setup
# ---------------------------

# Load the model with 8-bit quantization
bnb_8bit = BitsAndBytesConfig(
    load_in_8bit=True,                    # int8 linear layers
)

# Load the model with 4-bit quantization
bnb_4bit = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",            # QLoRA default
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=(
        torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    ),
)

# Load the model
model_name = "Qwen/Qwen2.5-1.5B"
pruner = LLMLayerPruner(
    model_name=model_name,
    # quant_config=bnb_4bit,
    default_percentages=[10, 20, 30, 40, 50],
    default_rank=16,
    default_max_heal_steps=500,
    default_max_qlora_steps=1000,
    blank_noise_std=0.01,                 # small noise for the blank layer
)

pruner.configure_profiles(
    ppl=None,
    single_heal=bnb_8bit,
    qlora=bnb_4bit,
    max_eval_seq_len=512,
)

builder = MixtureDataBuilder(pruner.tokenizer, max_length=512, seed=42, verbose=True)

# Build separate Train/Val/Test mixtures with token budgets per domain:
token_targets_by_split = {
    "train": {"syntax": 200_000, "code": 200_000, "math": 200_000},
    "test":  {"syntax": 50_000, "code": 50_000, "math": 50_000},
}

texts_by_split, lengths_by_split, summary_by_split = builder.build_split_mixtures(
    token_targets_by_split,
    val_from_train_when_missing=True
)


# Make dataloaders (you can omit a split by leaving it out of token_targets_by_split)
loaders = builder.make_dataloaders_for_splits(
    texts_by_split,
    batch_sizes={ "train": 4, "test": 8},
    num_workers=4,
    pin_memory=True,
    shuffle=False,
)

train_dl = loaders["train"]
eval_dl = loaders["test"]


# Path to your analysis CSVs from earlier steps
agg_csvs = {
    "weighted_mean": f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_weighted_mean.csv",
    # "minimax":       f"results/analysis/{pruner._slugify(model_name)}/{pruner._slugify(model_name)}_aggregate_minimax.csv",
}

# ---------------------------
# 2. Pre-heal pruning sweep
# ---------------------------
df_pre = pruner.run_single_shot_pruning_sweep(
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    train_dataloader=train_dl,
    strategies=["none", "tblock_blank", "tblock_avg", "tblock_lr_mean", "tblock_consensus"],
)
display(df_pre)

# ---------------------------
# 3. Single-layer heal sweep
# ---------------------------
df_heal = pruner.run_single_layer_heal_sweep(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    strategies=["tblock_blank", "tblock_avg", "tblock_lr_mean", "tblock_consensus"],
    lr=2e-4,
    max_steps=350,
    grad_accum=2,
)
display(df_heal)

# ---------------------------
# 4. Full-model QLoRA healing experiments
# ---------------------------
df_full = pruner.run_full_heal_experiments(
    train_dataloader=train_dl,
    eval_dataloader=eval_dl,
    agg_method_csvs=agg_csvs,
    qlora_lr=1e-4,
    max_qlora_steps=700,
    grad_accum=2,
)
display(df_full)

/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
/home/sobhan/anaconda3/envs/llm/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[Mixture] Fallback for domain 'code': requested 'test' but using 'train'
[Mixture] Built 'test': domains={'syntax': 50374, 'code': 50084, 'math': 50032} | used_splits={'syntax': 'test', 'code': 'train', 'math': 'test'}
[Mixture] Built 'train': domains={'syntax': 200046, 'code': 200126, 'math': 200034} | used_splits={'syntax': 'train', 'code': 'train', 'math': 'train'}

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 13.59it/s]

Baseline PPL: 12.409 (layers=28, hidden=1536)

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.04it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 14.99it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.95it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 14.98it/s]
Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.73it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.46it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.74it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.55it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.68it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.83it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 18.03it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.82it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.61it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.64it/s]
Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.65it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 19.20it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 19.73it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 19.80it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 19.87it/s]
Perplexity: 100%|██████████| 164/164 [00:08<00:00, 20.40it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 23.11it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 23.24it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 23.19it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 23.21it/s]
Perplexity: 100%|██████████| 164/164 [00:07<00:00, 23.26it/s]

[Pre-heal sweep] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_preheal_sweep.csv

,method,strategy,percent,selected_start,selected_end_inclusive,baseline_ppl,post_ppl,delta_ppl,inserted_idx,rank
0,weighted_mean,none,10,13,15,12.408719,11.563365,-0.845354,NaN,16
1,weighted_mean,tblock_blank,10,12,15,12.408719,12.192687,-0.216032,12.0,16
2,weighted_mean,tblock_avg,10,12,15,12.408719,12.123243,-0.285476,12.0,16
3,weighted_mean,tblock_lr_mean,10,12,15,12.408719,12.252200,-0.156519,12.0,16
4,weighted_mean,tblock_consensus,10,12,15,12.408719,12.221641,-0.187079,12.0,16
5,weighted_mean,none,20,11,16,12.408719,13.710756,1.302037,NaN,16
6,weighted_mean,tblock_blank,20,9,15,12.408719,16.036298,3.627578,9.0,16
7,weighted_mean,tblock_avg,20,9,15,12.408719,15.765839,3.357119,9.0,16
8,weighted_mean,tblock_lr_mean,20,9,15,12.408719,16.073602,3.664883,9.0,16
9,weighted_mean,tblock_consensus,20,9,15,12.408719,16.051596,3.642877,9.0,16
10,weighted_mean,none,30,9,16,12.408719,17.134082,4.725363,NaN,16
11,weighted_mean,tblock_blank,30,8,16,12.408719,19.718289,7.309570,8.0,16
12,weighted_mean,tblock_avg,30,8,16,12.408719,19.411582,7.002863,8.0,16
13,weighted_mean,tblock_lr_mean,30,8,16,12.408719,19.733177,7.324457,8.0,16
14,weighted_mean,tblock_consensus,30,8,16,12.408719,19.720212,7.311493,8.0,16
15,weighted_mean,none,40,8,18,12.408719,30.934981,18.526262,NaN,16
16,weighted_mean,tblock_blank,40,7,18,12.408719,40.010956,27.602237,7.0,16
17,weighted_mean,tblock_avg,40,7,18,12.408719,39.055418,26.646699,7.0,16
18,weighted_mean,tblock_lr_mean,40,7,18,12.408719,40.035429,27.626710,7.0,16
19,weighted_mean,tblock_consensus,40,7,18,12.408719,40.033488,27.624769,7.0,16
20,weighted_mean,none,50,7,20,12.408719,71.840211,59.431492,NaN,16
21,weighted_mean,tblock_blank,50,7,21,12.408719,167.906261,155.497542,7.0,16
22,weighted_mean,tblock_avg,50,7,21,12.408719,161.515002,149.106283,7.0,16
23,weighted_mean,tblock_lr_mean,50,7,21,12.408719,167.149121,154.740401,7.0,16
24,weighted_mean,tblock_consensus,50,7,21,12.408719,167.877872,155.469153,7.0,16

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 14.29it/s]

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 13.19it/s]

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 13.86it/s]

Perplexity: 100%|██████████| 164/164 [00:12<00:00, 12.78it/s]

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.06it/s]

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 13.80it/s]

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 15.01it/s]

Perplexity: 100%|██████████| 164/164 [00:11<00:00, 13.77it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.66it/s]

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 14.96it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 16.64it/s]

Perplexity: 100%|██████████| 164/164 [00:10<00:00, 14.94it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.66it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.05it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.41it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.35it/s]

Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.84it/s]

Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.81it/s]

Perplexity: 100%|██████████| 164/164 [00:09<00:00, 17.81it/s]

Perplexity: 100%|██████████| 164/164 [00:08<00:00, 18.89it/s]

[Single-layer heal] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_single_layer_heal.csv

,method,strategy,percent,selected_start,selected_end_inclusive,ppl_before_heal,ppl_after_heal,delta_ppl,inserted_idx,rank
0,weighted_mean,tblock_blank,10,12,15,12.192687,10.920452,-1.272236,12,16
1,weighted_mean,tblock_avg,10,12,15,12.123243,10.323148,-1.800095,12,16
2,weighted_mean,tblock_lr_mean,10,12,15,12.252200,10.603359,-1.648841,12,16
3,weighted_mean,tblock_consensus,10,12,15,12.221641,10.687746,-1.533895,12,16
4,weighted_mean,tblock_blank,20,9,15,16.036298,12.552041,-3.484256,9,16
5,weighted_mean,tblock_avg,20,9,15,15.765839,12.329089,-3.436750,9,16
6,weighted_mean,tblock_lr_mean,20,9,15,16.073602,12.913280,-3.160321,9,16
7,weighted_mean,tblock_consensus,20,9,15,16.051596,13.006622,-3.044974,9,16
8,weighted_mean,tblock_blank,30,8,16,19.718289,14.748783,-4.969506,8,16
9,weighted_mean,tblock_avg,30,8,16,19.411582,14.186360,-5.225222,8,16
10,weighted_mean,tblock_lr_mean,30,8,16,19.733177,14.608716,-5.124461,8,16
11,weighted_mean,tblock_consensus,30,8,16,19.720212,14.811692,-4.908520,8,16
12,weighted_mean,tblock_blank,40,7,18,40.010956,20.711346,-19.299610,7,16
13,weighted_mean,tblock_avg,40,7,18,39.055418,19.757107,-19.298311,7,16
14,weighted_mean,tblock_lr_mean,40,7,18,40.035429,20.997041,-19.038389,7,16
15,weighted_mean,tblock_consensus,40,7,18,40.033488,21.700881,-18.332608,7,16
16,weighted_mean,tblock_blank,50,7,21,167.906261,41.767350,-126.138911,7,16
17,weighted_mean,tblock_avg,50,7,21,161.515002,37.809495,-123.705507,7,16
18,weighted_mean,tblock_lr_mean,50,7,21,167.149121,39.977712,-127.171408,7,16
19,weighted_mean,tblock_consensus,50,7,21,167.877872,42.715695,-125.162177,7,16

Perplexity: 100%|██████████| 164/164 [00:22<00:00,  7.24it/s]

Perplexity: 100%|██████████| 164/164 [00:21<00:00,  7.49it/s]

Perplexity: 100%|██████████| 164/164 [00:21<00:00,  7.47it/s]

Perplexity: 100%|██████████| 164/164 [00:21<00:00,  7.70it/s]

Perplexity: 100%|██████████| 164/164 [00:20<00:00,  8.19it/s]

Perplexity: 100%|██████████| 164/164 [00:20<00:00,  8.03it/s]

Perplexity: 100%|██████████| 164/164 [00:18<00:00,  8.70it/s]

Perplexity: 100%|██████████| 164/164 [00:19<00:00,  8.59it/s]

Perplexity: 100%|██████████| 164/164 [00:19<00:00,  8.43it/s]

Perplexity: 100%|██████████| 164/164 [00:16<00:00,  9.70it/s]

Perplexity: 100%|██████████| 164/164 [00:16<00:00,  9.85it/s]

Perplexity: 100%|██████████| 164/164 [00:16<00:00, 10.13it/s]

Perplexity: 100%|██████████| 164/164 [00:15<00:00, 10.51it/s]

Perplexity: 100%|██████████| 164/164 [00:15<00:00, 10.66it/s]

Perplexity: 100%|██████████| 164/164 [00:14<00:00, 11.61it/s]

[Full-heal QLoRA] Saved: results/pruning/single-shot/qwen-qwen2.5-1.5b/qwen-qwen2.5-1.5b_full_heal_qlora.csv

,variant,percent,method,ppl_pre_qlora,ppl_post_qlora,adapters,ok,error
0,none,10,weighted_mean,11.563365,10.381425,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
1,tblock_blank_preheal,10,weighted_mean,12.192687,10.771351,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
2,tblock_avg_post_single_layer_heal,10,weighted_mean,10.323148,10.762662,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
3,none,20,weighted_mean,13.710756,12.001490,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
4,tblock_blank_preheal,20,weighted_mean,16.036298,12.903294,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
5,tblock_avg_post_single_layer_heal,20,weighted_mean,12.329089,12.788076,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
6,none,30,weighted_mean,17.134082,13.676097,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
7,tblock_blank_preheal,30,weighted_mean,19.718289,14.559466,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
8,tblock_avg_post_single_layer_heal,30,weighted_mean,14.186360,14.467624,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
9,none,40,weighted_mean,30.934981,17.460091,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
10,tblock_blank_preheal,40,weighted_mean,40.010956,19.131969,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
11,tblock_avg_post_single_layer_heal,40,weighted_mean,19.757107,18.944865,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
12,none,50,weighted_mean,71.840211,27.645302,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
13,tblock_blank_preheal,50,weighted_mean,167.906261,33.947998,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None
14,tblock_avg_post_single_layer_heal,50,weighted_mean,37.809495,33.689746,results/pruning/single-shot/qwen-qwen2.5-1.5b/...,True,None